### PR TITLE
fix ABICHECK_MERGE check

### PR DESCRIPTION
**Pull request by ipa-mdl**

### CODE REVIEW

**Comment by ipa-mdl** [comment]
Please "Rebase and merge".

**Comment by ipa-mdl** [comment]
I will include it in a backbprt PR

**Comment by 130s** [comment]
> Please "Rebase and merge".

Does that apply to all of merges on this repo or was it just this PR?

**Comment by ipa-mdl** [comment]
> Does that apply to all of merges on this repo or was it just this PR?

For those smaller changes I prefer a rebase-merge, because 2 commits (change+merge) are too much.
If the PR discussion is longer, a normal merge is an option as well.

**Pull request closed without merging**
