### PR TITLE
jade is EOL

### PR DESCRIPTION
**Pull request by ipa-mdl**
Use kinetic in tests and documentation instead.

[Travis](https://travis-ci.org/ros-industrial/industrial_ci/jobs/484397790) and [Gitlab](https://gitlab.com/ipa-mdl/industrial_ci/-/jobs/151684790)  builds are failing at `rosdep install` step.
Not sure what changed 2 weeks ago.

### CODE REVIEW

**Comment by ipa-mdl** [comment]
Ah, https://github.com/ros-infrastructure/rosdep/pull/647 happened

**Comment by ipa-mdl** [comment]
I'd like to roll out an fix first, because `indigo` and `lunar` will be EOL in a couple of months as well.

**Comment by 130s** [comment]
> I leave the decision up to you to merge as I'm not sure what you mean at https://github.com/ros-industrial/industrial_ci/pull/351#issuecomment-457908475

And it's WIP.

**Comment by ipa-mdl** [comment]
I meant #352, it will fix our builds as well.
We might want to keep the EOL jobs for now to test this fix.

**Pull request merged**
