### PR TITLE
run python unbuffered on travis

### PR DESCRIPTION
**Pull request by ipa-mdl**
does not solve it, but is related to #204 

Should this be the default in env.sh?

### CODE REVIEW

**Comment by ipa-mdl** [comment]
> Why not add PYTHONUNBUFFERED to a few of our jobs?

This would make either not difference at all or the tests would get as unstable as they are now  :-/
I am even thinking of enforcing it in `docker.env` with no way to opt out.

**Comment by 130s** [comment]
> This would make either not difference at all 

At least we might be able to catch possible issues that is based on the upstream. No?

> or the tests would get as unstable as they are now :-/

I'm confused.
- I understand there can be cases where enabling unbuffering could stabilize the test (#204).
- This PR only provides an option to enable unbuffering.

Am I wrong?

**Comment by ipa-mdl** [comment]
> This PR only provides an option to enable unbuffering.

Ah, that's where the confusion comes from.
This PR disables the buffering for all travis jobs (not only ours).

**Comment by ipa-mdl** [comment]
@130s: I have removed the whitespace, please review again.

**Pull request merged**
