### PR TITLE
Add support for BUILDER=catkin_tools_isolated_devel

### PR DESCRIPTION
**Pull request by ipa-mdl**
Middle ground between #700  and #702

### CODE REVIEW

**Review by rhaschke — COMMENTED** [review]
:-1:
`catkin build --isolate-devel` doesn't solve the issues addressed by #700 and #702.
The key point is to **not** use an `install` space at all. However, this option still installs.

**Comment by ipa-mdl** [comment]
> catkin build --isolate-devel doesn't solve the issues addressed by #700 and #702.
> The key point is to not use an install space at all. However, this option still installs.

I tested it locally and it fails with the same error as #700.

**Review by rhaschke — APPROVED** [review]
Sorry. I missed the point that you also dropped the `--install` option.
I think the option `--isolate-devel` is optional. I wasn't even aware of it before.

**Comment by ipa-mdl** [comment]
> I think the option --isolate-devel is optional. I wasn't even aware of it before.

This default is a merged devel space (similar to `catkin_make`), the isolated mode will result the same layout as `catkin_make_isolated`.
This should catch issues with implicit dependencies between packages of the same repository/workspace, but I am not 100% sure.

**Comment by ipa-mdl** [comment]
`--isolate-devel`:
```
$ tree -d .base/target_ws/devel/moveit_core/
.base/target_ws/devel/moveit_core/
├── include
│   └── moveit
├── lib
│   ├── moveit_core
│   ├── pkgconfig
│   └── python3
│       └── dist-packages
│           └── moveit
└── share
    └── moveit_core
        └── cmake

**Review by rhaschke — APPROVED** [review]

**Pull request merged**
