### PR TITLE
set TERM, run tests with tty

### PR DESCRIPTION
**Pull request by ipa-mdl**
pass `TERM` to docker, to get rid of the `NOTICE: Could not determine the width of the terminal. A default width of 80 will be used. This warning will only be printed once.` warnings.

### CODE REVIEW

**Comment by ipa-mdl** [comment]
canceled the other tests

**Comment by 130s** [comment]
The warning can still be seen e.g. [this line](https://travis-ci.org/ros-industrial/industrial_ci/jobs/202266336#L905)?

**Comment by ipa-mdl** [comment]
> The warning can still be seen e.g. this line?

Yes :-/
https://github.com/catkin/catkin_tools/blob/master/catkin_tools/common.py#L444 seems not to work, it requires a tty.

**Comment by ipa-mdl** [comment]
This did the trick.
So `catkin` does not read `TERM` anymore, but we should keep it for other tools.

**Pull request merged**
