### PR TITLE
Refactor ROS_REPO handling

### LINKED ISSUE #744: Sources list is modified even when DOCKER_IMAGE is passed.
In the docs, it says that Setting `DOCKER_IMAGE` disables the set-up of `ROS` based on `ROS_REPO` ([ref](https://github.com/ros-industrial/industrial_ci/blob/master/doc/index.rst#pulling-docker-image-from-an-online-hub)).

However, this is not true. See how in this minimal example, the `/etc/apt/sources` is changed even though `DOCKER_IMAGE` is provided:
```bash
$ rosrun industrial_ci run_ci DOCKER_IMAGE=osrf/ros:melodic-desktop \
                              ROS_REPO=testing \
                              BEFORE_INIT="cat /etc/apt/sources.list.d/ros*" \
                              AFTER_INIT="cat /etc/apt/sources.list.d/ros*; exit 1"

before_init
deb http://packages.ros.org/ros/ubuntu bionic main

after_init
deb [arch=amd64 signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros-testing/ubuntu bionic main

```

This is probably because of the code in these lines:
https://github.com/ros-industrial/industrial_ci/blob/c43b9a44265d8b498077e36edd53a45983a3b105/industrial_ci/src/workspace.sh#L143-L150

### PR DESCRIPTION
**Pull request by ipa-mdl**
`ROS_REPO` should not overwrite an existing ROS setup by default (fixes #744)
If `ROS_REPO` does no match the existing ROS setup, a warning will be raised.

### CODE REVIEW

**Comment by ipa-mdl** [comment]
My test cases pass and show the expected warnings:

* [ROS_REPO unset, no warning, main is used](https://github.com/ros-industrial/industrial_ci/pull/748/checks?check_run_id=3895155802#step:3:115)
* [ROS_REPO: testing, warning about conflict, testing is used](https://github.com/ros-industrial/industrial_ci/pull/748/checks?check_run_id=3895155874#step:3:120)

**Comment by ipa-mdl** [comment]
> Running the same as your test case but with ros:melodic gives exit code 1:

I added a test case for this, but it returns 2.
Did you test the right version?
Without the patches in this PR, the result will be 1. (which is what I tried to fix)

**Comment by InigoMoreno** [comment]
I made sure I am on the correct branch, but I still get error code 1:
```bash
$ git remote get-url origin                                    
https://github.com/ipa-mdl/industrial_ci
 
$ git status                                              
On branch fix/docker-image-ros-repo
Your branch is up to date with 'origin/fix/docker-image-ros-repo'.

nothing to commit, working tree clean

$ industrial_ci/scripts/run_ci DOCKER_IMAGE=ros:melodic\          
           AFTER_INIT="grep -r ros-testing /etc/apt && ici_exit 1 || ici_exit 2" > /dev/null
FAIL

$ echo $?                                                           
1

```

**Comment by InigoMoreno** [comment]
> Did you fetch the latest updates?

Yes

> I can't see any

I'll just paste it here:
When testing this with ros:melodic I get: 
```bash
apt-cache policy
N: Unable to locate package ros-noetic-ros-core
Using default ROS_REPO=testing
```
Is it possible it is getting the $ROS_DISTRO from my current workspace (noetic) instead of the one in the `DOCKER_IMAGE` (melodic)?

**Comment by InigoMoreno** [comment]
> I will clean this up and merge it later

Any update on this?

**Comment by ipa-mdl** [comment]
> Any update on this?

I pushed the clean version, will merge when all tests have passed.

**Pull request merged**
