### PR TITLE
Simplify rosdep, do not use robust flag

### PR DESCRIPTION
**Pull request by ipa-mdl**
As pointed out in #73, rosdep should not use `-r` for CI builds.
This PR even removes the manifest handling code.
Not sure why this was added at all.

### CODE REVIEW

**Comment by ipa-mdl** [comment]
> Not sure why this was added at all.

I will add a testcase for this.

**Comment by ipa-mdl** [comment]
I have tested it with a simple mockup (#96) test.

With this PR: https://travis-ci.org/ipa-mdl/industrial_ci/jobs/191319013:
* rosdep install dependencies from manifest.xml
* catkin detects manifest.xml and fallbacks to rosbuild, this fails because `ROS_PACKAGE_PATH` is not set-up properly

Wthout this PR: https://travis-ci.org/ipa-mdl/industrial_ci/jobs/191347515:
* rosdep uses `package.xml`
* manifest handling seems to fail anyway, I guess the script does not handle the symlink properly

Hybrid manifest package with master: https://travis-ci.org/ipa-mdl/industrial_ci/jobs/191351917:
* rosdep uses `package.xml`
* catkin behaves like in first case

manifest.xml breaks the tests in any case, this is not related to rosdep

So, I am going to merge this for the sake of simplicity.
And open a new issue for manifest.xml handling.

**Comment by 130s** [comment]
Thank you @ipa-mdl for the experiment https://github.com/ros-industrial/industrial_ci/pull/95#issuecomment-272205293! I didn't know `manifest.xml` wasn't handled as intended.

I'll make a new tag (yes I've been doing so) since now we removed a feature that regardless was not functioning, and send a brief update announce to swri ML.

**Comment by ipa-mdl** [comment]
> and send a brief update announce to swri ML.

 Please point to https://github.com/ros-industrial/industrial_ci/issues/97 as well.

**Comment by 130s** [comment]
Sent [an announcement](https://goo.gl/bmXGsE) but sorry @ipa-mdl, I mispelled your name...

**Pull request merged**
