### PR TITLE
Add matrix input to Github Action

### PR DESCRIPTION
**Pull request by ipa-mdl**
```yaml
jobs:
  industrial_ci:
    strategy:
      matrix:
        ROS_DISTRO: [melodic]
        ROS_REPO: [testing, main]
    runs-on: ubuntu-latest
    steps:
      - ...
      - uses: 'ros-industrial/industrial_ci@master'
        with:
          matrix: ${{toJSON(matrix)}}
```

`$` can be escaped with `$$`.
Without escaping, the variable substitution will happen immediately.

### CODE REVIEW

**Comment by ipa-mdl** [comment]
Not sure, if `matrix` is the right name. `config` might be better.

**Comment by gavanderhoorn** [comment]
> `$` can be escaped with `$$`.
> Without escaping, the variable substitution will happen immediately.

can or *must*?

The latter would be unfortunate.

**Comment by ipa-mdl** [comment]
> > $ can be escaped with $$.
> > Without escaping, the variable substitution will happen immediately.

> can or must?

Depends ;)
It works the same as for Gitlab CI.
For `BEFORE/AFTER_*` scripts you must escape it, for configuration variable early substitution  should be fine.

I could rewrite it to not support substitution at all, but then there might be no way to have substitution for Github Actions.

**Comment by ipa-mdl** [comment]
I just renamed the input to `config` and decided to not change the template yet (to be discussed in #590).

**Pull request merged**
