### PR TITLE
Catch apt error for ADDITIONAL_DEB

### PR DESCRIPTION
**Pull request by 130s**
Fix for #78

### CODE REVIEW

**Comment by 130s** [comment]
Could I ask @evenator for the review since you originally found the issue #78?

A caveat with this PR; I added a job to check true-negative (i.e. I want the job to fail upon error from the run), which I don't know yet how to capture on Travis CI. Right now the added jos is labeled `allow_failure` so that the entire jobs can pass but we just don't get notified for T-N. I [asked](http://stackoverflow.com/questions/39314067/to-capture-true-negative-on-travis-ci) if there's a way.

That said this PR is ready for review and merge if it's good.

**Comment by evenator** [comment]
LGTM

Regarding intended failures, is there a way you could invert the output of the script for that particular job so that a fail is a pass and vice versa?

**Comment by 130s** [comment]
> Regarding intended failures, is there a way you could invert the output of the script for that particular job so that a fail is a pass and vice versa?

Added a commit https://github.com/ros-industrial/industrial_ci/pull/79/commits/f7d09fa441237c7a3b648fb4907bd4509f4dfaea for that. Not elegant at all though.

**Comment by 130s** [comment]
> Regarding intended failures, is there a way you could invert the output of the script for that particular job so that a fail is a pass and vice versa?

Added a commit https://github.com/ros-industrial/industrial_ci/pull/79/commits/2b89d8e2d85ab55ff5d4a4836101e1c590887683 for that. Not elegant at all though.

**Comment by 130s** [comment]
Sorry for some debug commits; those unnecessary ones are now removed.

Travis passed for [the job in question](https://travis-ci.org/ros-industrial/industrial_ci/jobs/157803108).

**Comment by 130s** [comment]
@evenator could you verify again? Sorry to bother you but much have changed since your last +1.

**Comment by evenator** [comment]
This looks like it should work, but I don't like that the `_CI_INVERTERROR` option is only implemented for this particular case. I think it would be better to invert at the highest possible level (i.e. invert the output of the whole script).

Also, `_CI_INVERTERROR` isn't a very clear name to me. Maybe `_CI_EXPECT_FAIL`?

**Comment by 130s** [comment]
> I don't like that the _CI_INVERTERROR option is only implemented for this particular case. I think it would be better to invert at the highest possible level (i.e. invert the output of the whole script).

Actually that makes sense and I also thought that handling only particular case is too local. I opened a separate PR https://github.com/ros-industrial/industrial_ci/pull/80 and moved all associated changes there because implimenting the entire script sounds like a big project. 

Merging since the only remaining commit here is +1ed before.

**Pull request merged**
