### PR TITLE
added GitHub action and workflow

### PR DESCRIPTION
**Pull request by ipa-mdl**
addresses #343 

Example: https://github.com/ros-industrial/ros_canopen/blob/github-action/.github/workflows/main.yml

@gavanderhoorn, @agutenkunst: please test

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
@fmauch: you may be interested in this.

**Comment by gavanderhoorn** [comment]
@ipa-mdl: why are there so many empty lines in the log shown on the *Actions* tab for some of these runs?

Example (from [this](https://github.com/ros-industrial/ros_canopen/commit/1f7059adc0952df6210a8cfeaf7448bfc6e8499b/checks?check_suite_id=330277338) run):

```
[socketcan_bridge:install] make[2]: Leaving directory '/root/target_ws/build/socketcan_bridge'



[socketcan_bridge:install] /usr/bin/make -f CMakeFiles/roscpp_generate_messages_py.dir/build.make CMakeFiles/roscpp_generate_messages_py.dir/build




[socketcan_bridge:install] make[2]: Entering directory '/root/target_ws/build/socketcan_bridge'
```

**Comment by fmauch** [comment]
> @fmauch: you may be interested in this.

yes, indeed :-)

**Comment by fmauch** [comment]
I also get those empty lines during the actual build (see [this](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/commit/a024c383e1daf72b11881d38a26a82c753d0f457/checks?check_suite_id=331207717) run).

Abart from that this seems to be working nice.

**Comment by gavanderhoorn** [comment]
What does Actions allow that you're looking to use @fmauch?

**Comment by ipa-mdl** [comment]
> why are there so many empty lines in the log shown on the Actions tab for some of these runs?

I don't know..
I guess there is some post processing that adds this.
For now the output is not yet adapted for the GitHub environment.
One issue might be that I have to run the bash script from NodeJS :-/

**Comment by fmauch** [comment]
> What does Actions allow that you're looking to use @fmauch?

No special features. Coming more from a gitlab side, however, I enjoy having the CI tool closer coupled with the version control platform.

**Comment by ipa-mdl** [comment]
> why are there so many empty lines in the log shown on the Actions tab for some of these runs?

For now I blame https://github.com/catkin/catkin_tools/pull/587 in combination with a fault web console library, which does not detect `\r\n` .

**Pull request merged**
