### PR TITLE
Support for python3 with ROS1

### PR DESCRIPTION
**Pull request by ipa-mdl**
addresses #274 

It looks like ROS1 must be rebuilt from scratch in order to support python3.
So I add a `ROS_FROM_SCRATCH` feature, which uses `rosinstall_generator` to fetch all released sources.

The latter came in handy add support for `noetic` (based on Debian Buster) as well.

### CODE REVIEW

**Comment by ipa-mdl** [comment]
Works, but the auto-generation is not as powerful without https://github.com/ros-infrastructure/rosinstall_generator/issues/25 being fixed.
As a fallback `UPSTREAM_WORKSPACE` should point to a (generated) rosinstall file.

**Comment by arturmiller** [comment]
I have tried this out, with one of my repositories, but I have not been successful. I tried to run ROS melodic with Python3 and got as error message: "env: ‘rosdep’: No such file or directory". Am I missing something? Here is the build report: https://travis-ci.org/arturmiller/pybind11_examples/jobs/628120545#L186
And here is my travis.yml: https://github.com/arturmiller/pybind11_examples/blob/fix/ci/.travis.yml

**Comment by ipa-mdl** [comment]
@arturmiller:
If I recall it correctly, I got this error when a dependency pulled in `python-catkin-pkg` for some reason.
This would replace `python3-catkin-pkg` and therefore uninstall `python3-rosdep`.
I will have a look again.

**Comment by ipa-mdl** [comment]
> when a dependency pulled in `python-catkin-pkg`

In your case `python-rospkg`: https://travis-ci.org/arturmiller/pybind11_examples/jobs/628120545#L1154

**Comment by arturmiller** [comment]
Just now I see what it takes to support Python3. Your are right a dependency is not Python3 ready. This is the reason for my error. I was able to create a [minimal example](https://github.com/arturmiller/ros_py3), which is tested with Melodic and Python3.
I think I found a bug. If the project has no dependencies to other ROS packages, rosinstall-generator throws an [error](https://travis-ci.org/arturmiller/ros_py3/jobs/629752310#L739). This is why I have included roscpp as dependency. I don't know if this should be discussed in this PR.
I think this PR is very Important and I'm glad you created it. Many maintainer want to test their projects with Python3 and don't know how. [Python2 retires very soon](https://pythonclock.org/?1).

**Comment by ipa-mdl** [comment]
This is not needed anymore..
noetic is completely supported now and python 3 support for melodic seems  to introduduce more problems than it solves.

**Pull request closed without merging**
