### PR TITLE
[doc] Use install space by default

### PR DESCRIPTION
**Pull request by 130s**
<s>A quick patch to address #54. </s>

### CODE REVIEW

**Comment by 130s** [comment]
Please DO NOT REVIEW yet. It's WIP.

**Comment by 130s** [comment]
Please review. 

I've included a change to address #54 in a merged PR #67, simply by mistake.

With this PR is just a document update to explain that now the job uses `install` space by default.

**Comment by 130s** [comment]
Added a few commits to make this PR a bit more review-worthy.
- List capabilities at the top of README
- Elaborate package capability in `package.xml` (so that it shows up on http://wiki.ros.org/industrial_ci).

**Comment by 130s** [comment]
This is only a documentation change. @shaun-edwards @gavanderhoorn Could you review?
Summarizing the change:

- Update for install space usage #54 improvement
- Elaborate package capability in README, as well as `package.xml` (so that it shows up on http://wiki.ros.org/industrial_ci).
- Mention to a temporary prerelease test issue #64

**Comment by ipa-mdl** [comment]
I guess this is superseded by #113

**Comment by 130s** [comment]
> I guess this is superseded by #113

Agreed.

**Pull request closed without merging**
