### PR TITLE
prerelease-test cleanup and module preparations

### PR DESCRIPTION
**Pull request by ipa-mdl**
This is the last stop before splitting the `source_tests.sh` into functions (#98).

All scripts are now contained in `src` folder. The actual test scripts are contained in `src/tests`.
I have removed the install directive from the package for the time being.

The prerelease tests script does not expose variables anymore, installs less dependencies and calls the individual test scripts in folds.

### CODE REVIEW

**Comment by 130s** [comment]
> All scripts are now contained in src folder. 

+1. Other than being a fan of storing codes in subfolders, I really like the idea of making the codes portable #98.

> The actual test scripts are contained in src/tests.

I'm still trying to understand this. What would be the difference between the codes grouped into the 2 folders? Here is just my guess:

- `industrial_ci/src`: Test sequence definition. Variable to the environment?
- `industrial_ci/src/tests`: Test body definition. Environment-agnostic (e.g. container like docker, combined repo type (e.g. Github/GitLab etc.), CI system like Travis)?

> I have removed the install directive from the package for the time being.

That is fine.
I thought installing `industrial_ci` and test by itself could be benefital but  I guess no check has been implemented so far.

**Comment by ipa-mdl** [comment]
> I'm still trying to understand this. What would be the difference between the codes grouped into the 2 folders? Here is just my guess:

The final layout will look like:
```
src/
  ci_main.sh # entry point
  docker.sh # handling docker images/containers
  env. sh # default environment varibale
  workspace.sh # wstool, rosdep etc.
  builders/
    catkin.sh
  styles/
    travis.sh 
    console.sh # no folds
    youe_favourite_style.sh
  tests:
    ros_prerelease.sh 
    source_tests.sh
    catkin_lint.sh
    clang_format.sh
```

This design should enable to branch on TEST (like `moveit_ci`), STYLE and BUILDER etc.

> I thought installing industrial_ci and test by itself could be benefital but I guess no check has been implemented so far.

I have prepared an installable package, will follow in the next PR.
It contains a script that runs the CI tests locally in docker.

**Comment by 130s** [comment]
Sounds great. Thanks!

**Comment by 130s** [comment]
https://github.com/ros-industrial/industrial_ci/pull/117#issue-202873055
> #114 removed ssh-client from the installed package as it is just a recommended package.

Could you point to where the above statement refers to in this PR?

**Comment by ipa-mdl** [comment]
Sry, I linked the work PR. Change was introduced in https://github.com/ros-industrial/industrial_ci/commit/9f6efa8750e8efc4776c1b8e3a47130e907f85d0

**Pull request merged**
