### PR TITLE
install ssh client and pip

### PR DESCRIPTION
**Pull request by ipa-mdl**
as discussed https://github.com/ros-industrial/industrial_ci/issues/434#issuecomment-553124549

@fmessmer: please test

### CODE REVIEW

**Comment by fmessmer** [comment]
@ipa-mdl unfortunately, this does not seem to work:

```
Setting environment variables from .travis.yml

$ export ROS_REPO=ros

$ export VERBOSE_TESTS=false

$ export ROS_DISTRO=kinetic

$ export TARGET_WORKSPACE=.travis.kinetic.tagged.rosinstall

$ bash -c 'echo $BASH_VERSION'

4.3.48(1)-release

install

0.84s$ git clone --quiet --depth 1 https://github.com/ipa-mdl/industrial_ci.git .industrial_ci -b master-git-ssh

329.01s$ .industrial_ci/travis.sh

prepare_docker_image

24.56s>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

Function 'prepare_docker_image' returned with code '0' after 0 min 24 sec

init

198.12s>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

Function 'init' returned with code '0' after 3 min 18 sec

catkin_tools_setup

9.21s>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

Function 'catkin_tools_setup' returned with code '0' after 0 min 9 sec

setup_rosdep

10.22s>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

Function 'setup_rosdep' returned with code '0' after 0 min 10 sec

setup_target_workspace

81.61s>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>

Starting function 'setup_target_workspace'

debconf: delaying package configuration, since apt-utils is not installed

Selecting previously unselected package python-vcstool.

(Reading database ... 42633 files and directories currently installed.)

Preparing to unpack .../python-vcstool_0.2.4-1_all.deb ...

Unpacking python-vcstool (0.2.4-1) ...

Setting up python-vcstool (0.2.4-1) ...

EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

=== /root/target_ws/src/mojin_supported_robots (git) ===

Could not clone repository 'git@github.com:mojin-robotics/mojin_supported_robots': Cloning into '.'...

error: cannot run ssh: No such file or directory

fatal: unable to fork
```

**Comment by ipa-mdl** [comment]
@fmessmer: There was a typo, please test again.

**Comment by fmessmer** [comment]
yes, thanls this helps with the ssh issue - see https://github.com/ros-industrial/industrial_ci/issues/434#issuecomment-553529433

**Comment by ipa-mdl** [comment]
I guess I will merge this without 783b03c307f90080409f314cab435fe87ff1d3c9.

**Comment by fmessmer** [comment]
> I guess I will merge this later without [783b03c](https://github.com/ros-industrial/industrial_ci/commit/783b03c307f90080409f314cab435fe87ff1d3c9).

fine with me

**Comment by fmessmer** [comment]
just one more thing:
I'm seeing `debconf: delaying package configuration, since apt-utils is not installed` quite a lot during `install_target_dependencies` - would you like to install this, too? - or suppress the output?

**Comment by ipa-mdl** [comment]
> I'm seeing debconf: delaying package configuration, since apt-utils is not installed quite a lot during install_target_dependencies - would you like to install this, too? - or suppress the output?

This is a different issue.
Suppressing the output is rather complicated, because it gets written to stderr.
I am not sure if the non-interactive mode is configured correctly, though..

**Pull request merged**
