### PR TITLE
Remove problematic `--no-deps` flag from `catkin_run_tests` command.

### PR DESCRIPTION
**Pull request by miguelprada**
Related to #232.

### CODE REVIEW

**Comment by 130s** [comment]
I won't be able to do reviews until later this week. If this/possibly other PRs is crucial, @ipa-mdl please go head move on.

**Comment by miguelprada** [comment]
Not crucial for me whatsoever.

**Comment by ipa-mdl** [comment]
Let's wait for the review then :)

**Comment by ipa-mdl** [comment]
> Trying to think of why --no-deps has been passed to run_tests, I think it's just inherited from jsk_travis

If I remember it correcty, I have added to make the tests fail if some dependenccies haven't been declared, but I missed this whitelist problem.

**Pull request merged**
