### PR TITLE
[doc] Clarify clang check config file requirement.

### PR DESCRIPTION
**Pull request by 130s**
I don't know if those who use `clang-format` regularly should know already about this, but the file name requirement was a little tricky to me.

Please review @ipa-mdl @ipa-jfh

### CODE REVIEW

**Comment by ipa-mdl** [comment]
A link to https://clang.llvm.org/docs/ClangFormat.html should be sufficient, the others can be removed..

**Comment by ipa-jfh** [comment]
Maybe sth like this? (url is shown wrong)

* **CLANG_FORMAT_CHECK** (default: not set. Value range: ``[<format-style>|file]``): If set, run the `clang-format <https://clang.llvm.org/docs/ClangFormat.html>`_ check (Set the argument to ``file`` if the style configuration should be loaded from a ``.clang-format`` file, located in one of the parent directories of the source file).

**Comment by ipa-mdl** [comment]
I like @ipa-jfh's new version, but I would leave the brackets out

**Comment by 130s** [comment]
Hope my latest commit looks as exact as @ipa-jfh suggested.

**Comment by 130s** [comment]
Please re-review @ipa-mdl @ipa-jfh

**Comment by ipa-mdl** [comment]
I have add some fixes. Please squash all commits.

**Comment by ipa-jfh** [comment]
Looks good to me :)

**Comment by 130s** [comment]
Thanks for the review and fixes.

**Pull request merged**
