### PR TITLE
[doc] Clarification in readme (partly addresses #24).

### PR DESCRIPTION
**Pull request by 130s**
Basically this PR tries to add various clarification to readme.rst.
This PR originally tried to address the concern raised at https://github.com/ros-industrial/industrial_ci/issues/24#issuecomment-195428619

### CODE REVIEW

**Comment by 130s** [comment]
Also better address a comment https://github.com/ros-planning/moveit_core/pull/285#issuecomment-215879834

**Comment by 130s** [comment]
Now I feel like moving forward with this documentation update. Could anyone review?

**Comment by 130s** [comment]
@davetcoleman would you mind reviewing this since you've opened PRs before to readme?

**Comment by davetcoleman** [comment]
+1 I skimmed through the changes, but I need to focus my efforts on MoveIt!

**Comment by 130s** [comment]
Thanks!
And absolutely for MoveIt!

**Pull request merged**
