### PR TITLE
Migrate GitHub action to Environment file

### LINKED ISSUE #792: GitHub Actions: Deprecating save-state and set-output commands
I'm not exactly sure what action needs to be taken, but as of today I'm starting to see the following deprecation notice in my CI runs:
```
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```
see https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

and I see `set-output` being used here: https://github.com/ros-industrial/industrial_ci/blob/master/industrial_ci/src/folding/github_actions.sh#L29

### PR DESCRIPTION
**Pull request by mathias-luedtke**
set-output is deprecated

closes #792

### CODE REVIEW

**Review by rhaschke — APPROVED** [review]
Looks good to me.

**Comment by mathias-luedtke** [comment]
But https://github.com/ros-industrial/industrial_ci/actions/runs/3236891003/jobs/5303295252 is failing..
I have not found the issue yet.. looks like the GITHUB_OUTPUT is not an environment variable..

**Comment by rhaschke** [comment]
Hm. For some reason the variable is not recognized by GHA, resulting in a failed test:
https://github.com/ros-industrial/industrial_ci/actions/runs/3236891003/jobs/5303295252

**Comment by rhaschke** [comment]
I think you need to:
- forward the `GITHUB_OUTPUT` variable to the docker container
- and link the corresponding file into the docker container

**Comment by mathias-luedtke** [comment]
> I think you need to:
> 
> * forward the `GITHUB_OUTPUT` variable to the docker container
> * and link the corresponding file into the docker container

Yes, for the Docker-isolated builds..
Passing the variable might be enough.

**Comment by mathias-luedtke** [comment]
> Passing the variable might be enough.

No, it is not.
I will squash-merge this tomorrow, if the builds pass.

**Pull request merged**
