### PR TITLE
Fix tests and remove hard-coded script path

### PR DESCRIPTION
**Pull request by ipa-mdl**
The tests fails for master because somehow `catkin-tools` takes .ci_config as a package location.
(might be a bug..)

I took the chance to remove the need to name the directory `.ci_config`, which is the reason for copying the  files. In addition `ci_main.sh` does not rely on `travis.sh` anymore.

### CODE REVIEW

**Comment by 130s** [comment]
I'd like to test and see how things work by myself (later today hopefully), but the issue raised only occurs on Kinetic jobs doesn't it? If that's the case I have to admit that I might have not been as attentive as IJ jobs when I was writing the code...

**Comment by ipa-mdl** [comment]
> but the issue raised here only occurs on Kinetic jobs doesn't it?

No, travis build fails for the master:
https://travis-ci.org/ros-industrial/industrial_ci/builds/180789707

**Comment by ipa-mdl** [comment]
Now the kinetic non-prerelease test fail, I missed something..

**Comment by ipa-mdl** [comment]
should be fixed now, we will see in 2 hours ;)

**Comment by ipa-mdl** [comment]
I have extracted all(?) to-be-passed environment variables to docker.env.
The TRAVIS_* ones should be replaced by generic ones later..

**Comment by ipa-mdl** [comment]
@130s: some jobs failed to download packages, can you restart them? 
https://travis-ci.org/ros-industrial/industrial_ci/jobs/184463311
https://travis-ci.org/ros-industrial/industrial_ci/jobs/184463312

https://travis-ci.org/ros-industrial/industrial_ci/jobs/184463320 is supposed to fail?

**Comment by 130s** [comment]
> some jobs failed to download packages, can you restart them?
> https://travis-ci.org/ros-industrial/industrial_ci/jobs/184463311
> https://travis-ci.org/ros-industrial/industrial_ci/jobs/184463312

Done.

@shaun-edwards Can we add @ipa-mdl admin (/ whatever necessary) privilege so that he can restart Travis jobs?

**Comment by 130s** [comment]
Seems reasonable, merging.

Except one thing that I'm curious; 

> The tests fails for master because somehow catkin-tools takes .ci_config as a package location. (might be a bug..)

I want to see how this happened. I doesn't find the associated SHA in https://travis-ci.org/ros-industrial/industrial_ci/pull_requests. If you could show the link to the job page that'll be great
(If it's something in the upstream we gotta fix in the upstream).

**Comment by ipa-mdl** [comment]
https://travis-ci.org/ros-industrial/industrial_ci/builds/180789707
It cannot be related to the last PR.
I guess catkin was synced and therefore behaved differently.

**Comment by shaun-edwards** [comment]
I've added @ipa-mdl as an admin (sorry for the delay).  For what it's worth, I think @130s has the ability to do this as well.  Go to  `Settings` -> `Collaborators & Teams`

**Comment by ipa-mdl** [comment]
@shaun-edwards: Thanks!

**Pull request merged**
