### PR TITLE
fix the error handling in run_travis

### LINKED ISSUE #262: [run_travis] AttributeError: 'list' object has no attribute 'proc'
With #261 I'm running `run_travis` and getting error.

```
$ roscd swri_profiler
$ git branch -vv
* master 71ae85e [origin/master] Merge pull request #11 from pjreed/install-files
$ git log -1
commit 71ae85e1956a1e10b5d73502015205e15c55f384
Merge: b15c768 54607db
Author: P. J. Reed <pjreed@users.noreply.github.com>
Date:   Thu Nov 2 14:24:24 2017 -0500

    Merge pull request #11 from pjreed/install-files
    
    Install Python scripts & HTML files

$ ~/industrial_ci/industrial_ci/scripts/run_travis
Job 1: ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
Job 2: ROS_REPOSITORY_PATH=http://packages.ros.org/ros-shadow-fixed/ubuntu
run all with /home/n130s/industrial_ci/industrial_ci/scripts/run_travis -
$ 
$ ~/industrial_ci/industrial_ci/scripts/run_travis .
Job 1: ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
Job 2: ROS_REPOSITORY_PATH=http://packages.ros.org/ros-shadow-fixed/ubuntu
run all with /home/n130s/industrial_ci/industrial_ci/scripts/run_travis -
$ ~/industrial_ci/industrial_ci/scripts/run_travis -
Running job 1: /home/n130s/industrial_ci/industrial_ci/scripts/run_ci /home/n130s/ROS/kinetic/cws_pickone/src/swri-robotics/swri_profiler  ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
Testing /home/n130s/ROS/kinetic/cws_pickone/src/swri-robotics/swri_profiler
ROS distro '' is not supported
Tests failed exit code '1'
Failed job 1: /home/n130s/industrial_ci/industrial_ci/scripts/run_ci /home/n130s/ROS/kinetic/cws_pickone/src/swri-robotics/swri_profiler  ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
Traceback (most recent call last):
  File "/home/n130s/industrial_ci/industrial_ci/scripts/run_travis", line 170, in <module>
    main(os.path.abspath(os.path.dirname(__file__)), sys.argv)
  File "/home/n130s/industrial_ci/industrial_ci/scripts/run_travis", line 167, in main
    sys.exit(bash.proc)
AttributeError: 'list' object has no attribute 'proc'

$ ~/industrial_ci/industrial_ci/scripts/run_travis . -
Running job 1: /home/n130s/industrial_ci/industrial_ci/scripts/run_ci /home/n130s/ROS/kinetic/cws_pickone/src/swri-robotics/swri_profiler  ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
Testing /home/n130s/ROS/kinetic/cws_pickone/src/swri-robotics/swri_profiler
ROS distro '' is not supported
Tests failed exit code '1'
Failed job 1: /home/n130s/industrial_ci/industrial_ci/scripts/run_ci /home/n130s/ROS/kinetic/cws_pickone/src/swri-robotics/swri_profiler  ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
Traceback (most recent call last):
  File "/home/n130s/industrial_ci/industrial_ci/scripts/run_travis", line 170, in <module>
    main(os.path.abspath(os.path.dirname(__file__)), sys.argv)
  File "/home/n130s/industrial_ci/industrial_ci/scripts/run_travis", line 167, in main
    sys.exit(bash.proc)
AttributeError: 'list' object has no attribute 'proc'
```

### PR DESCRIPTION
**Pull request by ipa-mdl**
fixes #262

### CODE REVIEW

**Comment by ipa-mdl** [comment]
@130s: please test

**Comment by ipa-mdl** [comment]
For some reason I have used "globals" instead of "global"..
Please try again.

**Comment by 130s** [comment]
Hmm...
```
$ cd industrial_ci && git log -1
commit 1f8bbef230da217848b43738696ec0770a359abb
Author: Mathias Lüdtke <mathias.luedtke@ipa.fraunhofer.de>
Date:   Sat Feb 3 22:24:54 2018 +0100

    [run_travis] parse 'global' instead of 'globals'

$ ~/non_synced/cws_swri_profiler/src/swri-robotics/swri_profiler
$ git branch -vv
* master 71ae85e [origin/master] Merge pull request #11 from pjreed/install-files

$ ~/industrial_ci/industrial_ci/scripts/run_travis .
Job 1: ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
Job 2: ROS_REPOSITORY_PATH=http://packages.ros.org/ros-shadow-fixed/ubuntu
run all with /home/n130s/industrial_ci/industrial_ci/scripts/run_travis -

$ ~/industrial_ci/industrial_ci/scripts/run_travis -
Traceback (most recent call last):
  File "/home/n130s/industrial_ci/industrial_ci/scripts/run_travis", line 170, in <module>
    main(os.path.abspath(os.path.dirname(__file__)), sys.argv)
  File "/home/n130s/industrial_ci/industrial_ci/scripts/run_travis", line 160, in main
    cmd = ' '.join(run_ci + [job_envs[i]])
TypeError: sequence item 2: expected string, tuple found
```

**Comment by ipa-mdl** [comment]
Yeah, another bug ;)

**Comment by ipa-mdl** [comment]
@130s: `swri_profiler` works now ;)

**Comment by 130s** [comment]
Gets stuck at the following line. Am I missing anything? Looks like `run_travis` is a Python script that doesn't import anything else from industrial_ci, I'm just calling it specifying its path. 

> RUN sed -i "/^# deb.*multiverse/ s/^# //" /etc/apt/sources.list     && apt-get update -qq     && apt-get -qq install --no-install-recommends -y         build-essential         python-catkin-tools         python-pip         python-rosdep         python-wstool         ros-jade-catkin         ssh-client     && apt-get clean     && rm -rf /var/lib/apt/lists/*`

```
$ cd industrial_ci && git log -1                                                       
commit fce5f4a3ae51f48a6b142da2b5691f6c598bd538
Author: Mathias Lüdtke <mathias.luedtke@ipa.fraunhofer.de>
Date:   Mon Jun 4 00:48:58 2018 +0200

    fix tuple issue

$ cd swri_profiler
$ ~/link/industrial_ci/industrial_ci/scripts/run_travis -
Running job 1: /home/n130s/link/industrial_ci/industrial_ci/scripts/run_ci /home/n130s/cws_indicarice/src/swri-robotics/swri_profiler USE_DEB=true ROS_DISTRO="jade" ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
Testing /home/n130s/cws_indicarice/src/swri-robotics/swri_profiler
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
Building image 'industrial-ci/jade/ubuntu:trusty':
FROM ubuntu:trusty

RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections

RUN apt-get update -qq     && apt-get -qq install --no-install-recommends -y apt-utils gnupg wget ca-certificates lsb-release

RUN echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list
RUN apt-key adv --keyserver "hkp://ha.pool.sks-keyservers.net" --recv-key "0xB01FA116"     || { wget "https://raw.githubusercontent.com/ros/rosdistro/master/ros.key" -O - | apt-key add -; }

RUN sed -i "/^# deb.*multiverse/ s/^# //" /etc/apt/sources.list     && apt-get update -qq     && apt-get -qq install --no-install-recommends -y         build-essential         python-catkin-tools         python-pip         python-rosdep         python-wstool         ros-jade-catkin         ssh-client     && apt-get clean     && rm -rf /var/lib/apt/lists/*

^CTraceback (most recent call last):
  File "/home/n130s/link/industrial_ci/industrial_ci/scripts/run_travis", line 170, in <module>
    main(os.path.abspath(os.path.dirname(__file__)), sys.argv)
  File "/home/n130s/link/industrial_ci/industrial_ci/scripts/run_travis", line 164, in main
    proc.communicate(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 797, in communicate
    self.wait()
  File "/usr/lib/python2.7/subprocess.py", line 1392, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/usr/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
KeyboardInterrupt
```
Passing `ROS_DISTRO` manually but I still see `jade`, and it's stuck at the same place.
```
n130s@130s-p50:~/non_synced/cws_swri_profiler/src/swri_profiler$ ~/link/industrial_ci/industrial_ci/scripts/run_travis - -- ROS_DISTRO=kinetic
Running job 1: /home/n130s/link/industrial_ci/industrial_ci/scripts/run_ci /home/n130s/cws_indicarice/src/swri-robotics/swri_profiler USE_DEB=true ROS_DISTRO="jade" ROS_REPOSITORY_PATH=http://packages.ros.org/ros/ubuntu
Testing /home/n130s/cws_indicarice/src/swri-robotics/swri_profiler
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
Building image 'industrial-ci/jade/ubuntu:trusty':
FROM ubuntu:trusty

RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections

RUN apt-get update -qq     && apt-get -qq install --no-install-recommends -y apt-utils gnupg wget ca-certificates lsb-release

RUN echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list
RUN apt-key adv --keyserver "hkp://ha.pool.sks-keyservers.net" --recv-key "0xB01FA116"     || { wget "https://raw.githubusercontent.com/ros/rosdistro/master/ros.key" -O - | apt-key add -; }

RUN sed -i "/^# deb.*multiverse/ s/^# //" /etc/apt/sources.list     && apt-get update -qq     && apt-get -qq install --no-install-recommends -y         build-essential         python-catkin-tools         python-pip         python-rosdep         python-wstool         ros-jade-catkin         ssh-client     && apt-get clean     && rm -rf /var/lib/apt/lists/*
```

**Comment by ipa-mdl** [comment]
> Passing ROS_DISTRO manually but I still see jade

Currently the values in `.travis.yml` take precedence. But overwriting but might be more intuitive..

> Looks like run_travis is a Python script that doesn't import anything else from industrial_ci, I'm just calling it specifying its path.

Should work.

> Gets stuck at the following line

This passes after 2min on my system.

**Comment by ipa-mdl** [comment]
@130s: please try again

**Comment by 130s** [comment]
Same steps in https://github.com/ros-industrial/industrial_ci/pull/265#issuecomment-396128327 worked on my computer! Merging.

**Pull request merged**
