### PR TITLE
deprecate legacy branch

### PR DESCRIPTION
**Pull request by ipa-mdl**
~~closes~~ #387

### CODE REVIEW

**Comment by ipa-mdl** [comment]
This will be accompanied by a ROS discourse post

**Comment by 130s** [comment]
> This PR looks

Nevermind mOm

**Comment by 130s** [comment]
Also, I think somewhere we should clarify "support" plan (answering questions, future development) assuming `master` will be the default and the maintenance focus. So in`legacy` branch at the top of the doc we may want to put a notice.

**Comment by ipa-mdl** [comment]
>  I think somewhere we should clarify "support" plan (answering questions, future development)

Good point!
I would describe it like this:

* no future development for `legacy`, bug fixing will continue as long as feasible
* support will be minimal: bug fixing and support for features that can only be found in `legacy`.

I will update the PR to reflect at least the first point

**Pull request merged**
